package com.dev.docscannerpdf.presentation

enum class MainScreen {
    Dashboard,
    AppLock,
    Onboarding,
    CloudSync,
    Premium,
    FeatureValidation,
    ApiHealth,
    BackupRestore,
    Settings,
    PdfViewer,
    LockPdf,
    UnlockPdf,
    SignPdf,
    WatermarkPdf,
    PdfToWord,
    PdfToImages,
    EditPdf,
    MergePdf,
    SplitPdf,
    ImagesToPdf,
    CompressPdf,
    PdfTools,
    DocumentLibrary,
    MultiPageEditor,
    CropEditor,
    LiveScanner,
    ImageImportReview,
    ImageEditor,
    ImportedImagePreview
}
